### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by musdfakoc** [Olya-M/imaginary-houses-GAN#1]
hey there, thanks for the great work. Can you share your dataset too?
Thanks already.

**Comment by Olya-M** [comment]
Sure! Thank you, I've been forgetting to add it. Here is the google drive link: [https://drive.google.com/file/d/1O3FCo4ey0LzpNbplpazqllK67OCGmcmk/view?usp=sharing](https://drive.google.com/file/d/1O3FCo4ey0LzpNbplpazqllK67OCGmcmk/view?usp=sharing)
I'll add it to the readme, too. Please let me know in case it doesn't work
